#
#
# This is a sample newrelic_plugin.yml file. Please move this file
# to the following location if it is not already there:
#
#     ./config/newrelic_plugin.yml
#
# Where the current directory is the directory where your main program resides and is your current
# directory when you run the main program.
#
# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: '3d57f8f22e7323d0790abefc97be8dbaf335c83f'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  verbose: 0
  poll: 60
#
# Agent Configuration:
#
agents:
  logwatcher:
    # Full path to the the log file
    log_path: tmp.log
    # Returns the number of matches for this term. Use Linux Regex formatting.
    # Default: "[Ee]rror"
    term: "[Ee]rror   "
    # Provide any options to pass to grep when running.
    # For example, to count non-matching lines, enter 'v'.
    # Use the abbreviated format ('v' and not 'invert-match').
    grep_options:
  mpstat:
    # The command used to display MP statistics
    command: mpstat
    # Report current usage as the average over this many seconds.
    interval: 2
  haproxy:
    # URI of the haproxy CSV stats url. See the 'CSV Export' link on your haproxy stats page (example stats page: http://demo.1wt.eu/).
    uri: http://demo.1wt.eu/;csv
    # The name of the proxy to monitor. Proxies are typically listed in the haproxy.cfg file.
    proxy: www
    # If multiple proxies have the same name, specify which proxy you want to monitor (ex: 'frontend' or 'backend')."
    proxy_type: BACKEND
    # If protected under basic authentication provide the user name
    user:
    # If protected under basic authentication provide the password.
    password:
  resque:
    # Redis connection string: 'hostname:port' or 'hostname:port:db' or 'redis://user:password@hostname:port:db'
    redis: localhost:6379
    # Resque namespace
    namespace:

